name             'df_php'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures df_php'
long_description 'Installs/Configures df_php'
version          '0.1.0'
